### ISSUE TITLE
did it support not.toBeObservable?

### ISSUE THREAD

**Issue by yutsengwei** [synapse-wireless-labs/jasmine-marbles#11]
Hi guys,
     as title, I am trying to write a test with marbles and Jasmine in Angular. 

I have a effect with a filter, 
for example: 
loadDatas$: Observable<Action> = this.actions$.ofType(LOAD_DATAS_ACTION).pipe(
withLatestFrom(this.store.select(getDatas), (action, datas) =>datas),
filter(data => !data.length),
switchMap(() => {
return this.dataApi.find().pipe(
.....

basically, it won't do switch map if the data length > 0. 

I wanna test data length > 0,
so I try expect(effects.loadTrials$).not.toBeObservable(expected); 
but not what I expect...

did I try something wrong?

**Comment by krzysztof-grzybek** [comment]
Hi @yutsengwei
Better late than never xD I just encountered this issue. It's a bug because under the hood [it uses regular `expect`](https://github.com/synapse-wireless-labs/jasmine-marbles/blob/master/index.ts#L153). If it would use standard jasmine customer matcher API (returning `{ pass: boolean, message: string}`, it would work.

**Comment by skyleguy** [comment]
I am doing something similar. 

any ideas as to what we can expect instead of doing .not.toBeObservable(ourObservable) ?

it looks like what it is receiving is "Array []" but no matter what i change the expected value to it is not matching exactly

**Comment by skyleguy** [comment]
actually just got the answer by accident:

const expected = cold('')
expect(effects.myEffect$).toBeObservable(expected)

**Comment by brandonroberts** [comment]
Fixed via #55
