### ISSUE TITLE
Trim marble strings

### ISSUE THREAD

**Issue by MikeRyanDev** [synapse-wireless-labs/jasmine-marbles#3]
Using spacing to align marble diagrams is essential for creating readable tests. Currently leading and trailing whitespace characters has unintended side effects. Correct fix is to trim the string diagrams.

**Comment by aboyton** [comment]
Any chance of getting this fixed? Other libraries like https://github.com/kwonoj/rx-sandbox have this and it's kinda needed if you want to use Prettier with this library.

**Comment by bcabanes** [comment]
Hi @aboyton,
2 PR have been created for this issue and are waiting review/approbation by @MikeRyanDev. Be patient, I'm sure he will take a look when he'll have time.

Have a nice day!

**Comment by aboyton** [comment]
Thanks @bcabanes. One of the PRs is mine, the other is yours 😄 

I asked as I noticed that you have 4 PRs from May which have not been reviewed and there's been nothing pushed to this repo since March and so I was just wondering how active this repo was.

I'm presently using https://github.com/kwonoj/rx-sandbox which I'm reasonably happy with so I'm in no rush at all. This library was recommended by @phillipzada at [Angular Conf Australia](https://www.angularconf.com.au/) and so I thought I'd give it a go.

**Comment by brandonroberts** [comment]
Fixed via #26
