### ISSUE TITLE
toHaveSubscriptions not working

### ISSUE THREAD

**Issue by Karolis92** [synapse-wireless-labs/jasmine-marbles#44]
after update from 0.4.1 to 0.5.0 my test broke on `toHaveSubscriptions`:
```
Expected $[1] to be a kind of SubscriptionLog, but was SubscriptionLog({ subscribedFrame: 30, unsubscribedFrame: 50 }).
    at <Jasmine>
    at compare (http://localhost:9876/_karma_webpack_/node_modules/jasmine-marbles/index.js:57:1)
    at <Jasmine>
```

Tests are for ngrx effects. Versions:
```
"jasmine-marbles": "0.5.0",
"rxjs": "6.5.2"
"@ngrx/effects": "8.2.0",
```

I have no idea what's wrong. 0.4.1 works fine when rolled back

**Comment by fluggo** [comment]
The problem here is that SubscriptionLog is being imported in two different ways:

* `node_modules/rxjs/internal/testing/SubscriptionLog.js`
* `node_modules/rxjs/_esm2015/internal/testing/SubscriptionLog.js`

Jasmine is upset that the types are different. Unfortunately, this leaves me with no way to run jasmine-marbles, as setup doesn't work right when rolled back to 0.4.1.

**Comment by fluggo** [comment]
Reported as [angular-cli#16941](https://github.com/angular/angular-cli/issues/16941).

As a workaround, add this to tsconfig.json:

```jsonc
{
  "compileOnSave": false,
  "compilerOptions": {
    ...
    "paths": {
      "rxjs/*": [
        "node_modules/rxjs/_esm2015/*"
      ],
    },
    ...
  },
}
```

**Comment by fluggo** [comment]
Angular-CLI reports that this is a side effect of jasmine-marbles deep importing into RxJS. It should not be using internal paths.

**Comment by HedCET** [comment]
+1

**Comment by brandonroberts** [comment]
Closed via https://github.com/synapse-wireless-labs/jasmine-marbles/pull/64
